### ISSUE TITLE
not an issue - confusion around runtime nvidia

### ISSUE THREAD

**Issue by johndpope** [enric1994/detectron-api#1]
https://github.com/enric1994/detectron-api/blob/96bbc806ccba98342e3ce2f3f8c66ba736cd8d82/docker/docker-compose.yml#L16

from what I read - runtime nvidia is deprecated....

I follow all the install instructions - and get to docker-compose up

docker version                                                       
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:      

docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6

```shell
Creating detectron-api ... error

ERROR: for detectron-api  Cannot create container for service detectron-api: Unknown runtime specified nvidia

ERROR: for detectron-api  Cannot create container for service detectron-api: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.



```
but even facebook detectron2 uses this still.
.https://github.com/facebookresearch/detectron2/tree/master/docker
Do I need to install the deprecated nvidia-docker2 to get this working?

```shell
sudo docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
Thu Apr 23 00:04:06 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K2200        Off  | 00000000:03:00.0  On |                  N/A |
| 43%   49C    P0     2W /  39W |    607MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

I tried swapping gpus all in the docker-compose yaml file - but no joy.

**Comment by enric1994** [comment]
Hey @johndpope I remember having some issues when installing Nvidia-Docker.

Indeed, I installed nvidia-docker2 to make it work following the instructions [here](https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))

Let me know if that helps

**Comment by johndpope** [comment]
I ran this command
**sudo apt-get install nvidia-docker2**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nvidia-docker2 is already the newest version (2.2.2-1).
The following packages were automatically installed and are no longer required:
  fonts-liberation2 fonts-opensymbol gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 gir1.2-gudev-1.0 gir1.2-udisks-2.0 golang-docker-credential-helpers
  grilo-plugins-0.3-base gstreamer1.0-gtk3 libboost-date-time1.65.1 libboost-filesystem1.65.1 libboost-iostreams1.65.1 libboost-locale1.65.1 libcdr-0.1-1
  libclucene-contribs1v5 libclucene-core1v5 libcmis-0.5-5v5 libcolamd2 libdazzle-1.0-0 libe-book-0.1-1 libedataserverui-1.2-2 libeot0 libepubgen-0.1-1
  libetonyek-0.1-1 libexiv2-14 libfreerdp-client2-2 libfreerdp2-2 libfwup1 libgc1c2 libgee-0.8-2 libgexiv2-2 libgom-1.0-0 libgpgmepp6 libgpod-common libgpod4
  liblangtag-common liblangtag1 liblirc-client0 liblua5.3-0 libmediaart-2.0-0 libmspub-0.1-1 libodfgen-0.1-1 libqqwing2v5 libraw16 librevenge-0.0-0 libsgutils2-2
  libssh-4 libsuitesparseconfig5 libvncclient1 libwayland-egl1-mesa libwinpr2-2 libxapian30 libxmlsec1 libxmlsec1-nss lp-solve media-player-info python-asn1crypto
  python-backports.ssl-match-hostname python-cached-property python-certifi python-cffi-backend python-chardet python-cryptography python-docker python-dockerpty
  python-dockerpycreds python-docopt python-enum34 python-funcsigs python-functools32 python-idna python-ipaddress python-jsonschema python-mock python-openssl
  python-pbr python-pkg-resources python-requests python-six python-texttable python-urllib3 python-websocket python-yaml python3-mako python3-markupsafe syslinux
  syslinux-common syslinux-legacy usb-creator-common
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

and / it didn't seem to install anything - but inexplicably things started working - thanks.


```shell

➜  docker git:(master) ✗ docker-compose up  
Creating network "docker_default" with the default driver
Creating detectron-api ... done
Attaching to detectron-api
detectron-api    | Failed to load OpenCL runtime
model_final_a3ec72.pkl: 254MB [03:16, 1.29MB/s]                            * Serving Flask app "app" (lazy loading)
detectron-api    |  * Environment: production
detectron-api    |    WARNING: This is a development server. Do not use it in a production deployment.
detectron-api    |    Use a production WSGI server instead.
detectron-api    |  * Debug mode: on
detectron-api    | 
detectron-api    |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
detectron-api    |  * Restarting with stat
detectron-api    | Failed to load OpenCL runtime
detectron-api    |  * Debugger is active!
detectron-api    |  * Debugger PIN: 971-524-778
detectron-api    | 172.18.0.1 - - [23/Apr/2020 00:49:47] "POST / HTTP/1.1" 200 -
detectron-api    | 172.18.0.1 - - [23/Apr/2020 00:50:34] "POST / HTTP/1.1" 200 -



```

can see api working. 

I'm wanting to build a batch processor in the cloud for videos as part of a pipeline for further creative work - do you have any down time right now?

**Comment by enric1994** [comment]
Sure! Drop me an email :)

**Comment by johndpope** [comment]
I found this Background-Matting repo which does several extra steps to rip apart an mp4 and glue images back together with new background of choice / exactly the problem I wanted to solve / no api / no docker support though -  jury is out on whether detectron2 can outperform -  I suspect it can. but needs testing https://github.com/senguptaumd/Background-Matting
